# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    shm_size: "256m"  # Increase shared memory size
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Use a named volume
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=your_strong_password 
      - POSTGRES_USER=admin
      - POSTGRES_DB=aradng
    networks:
      - backend_network

  backend:
    build: .\backend
    restart: always
    container_name: backend_nest
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3001/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_URI=db
      - POSTGRES_USER=admin
      - POSTGRES_USER_PASS=your_strong_password
      - POSTGRESS_DATABASE=aradng
      - APP_PORT=3001
      - ADMIN_EMAIL=admin@email.com
      - ADMIN_PASSWORD=secretpass
      - JWT_SECRECT=supersecrectssh
      - ADMIN_NAME=admin
    depends_on:
      - db
    networks:
      - backend_network
 
  scripts:
    build: .\scripts
    container_name: scripts_app
    environment:
      - BACKEND_URI=http://backend:3001
    depends_on:
       backend:
          condition: service_healthy
    command: "node populateDb.js && exit 0"
    networks:
      - backend_network

  frontend:
    build: .\
    restart: always
    container_name: frontend_react
    environment:
      - VITE_BACKEND_URI=http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: 