# Use an official Node.js image as a base
FROM node:20.12.0

# Set the working directory to /app
WORKDIR /app
COPY . .
# Install the dependencies
RUN npm install

# Copy the application code to the working directory


